# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='blitzuser',
            name='avatar',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BlitzUser'),
        ),
    ]
