# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('accounts', '0002_auto_20160405_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='blitzuser',
            name='avatar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
    ]
