# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blitz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blitzUser1', to='accounts.BlitzUser')),
                ('user2', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blitzUser2', to='accounts.BlitzUser')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('startDate', models.DateTimeField(default=0)),
                ('endDate', models.DateTimeField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=images.models.user_directory_path)),
                ('chapter', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='images.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('dislikedBy', models.ManyToManyField(related_name='dislikes', to='accounts.BlitzUser')),
                ('likedBy', models.ManyToManyField(related_name='likes', to='accounts.BlitzUser')),
                ('topic', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='images.Topic')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.BlitzUser')),
            ],
        ),
        migrations.AddField(
            model_name='userchapter',
            name='userTopic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='images.UserTopic'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='topic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='images.Topic'),
        ),
        migrations.AddField(
            model_name='blitz',
            name='userTopic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='images.UserTopic'),
        ),
        migrations.AddField(
            model_name='blitz',
            name='winner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='accounts.BlitzUser'),
        ),
    ]
