# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 19:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchapter',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 3, 19, 2, 37, 933853, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
