# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_userchapter_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchapter',
            name='userTopic',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='images.UserTopic'),
        ),
    ]
