# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20160704_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertopic',
            options={'ordering': ['-timestampUpdated']},
        ),
    ]
