# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20160704_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blitz',
            name='userTopic',
        ),
        migrations.RemoveField(
            model_name='blitz',
            name='winner',
        ),
        migrations.AddField(
            model_name='blitz',
            name='topic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='images.Topic'),
        ),
    ]
